# Generated by Django 3.2.20 on 2023-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_actived',
            field=models.BooleanField(default=False, verbose_name='邮箱验证'),
        ),
    ]
