# Generated by Django 3.2.20 on 2023-08-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
    ]
