# Generated by Django 3.2.20 on 2023-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinfo_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
